language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
addons:
  apt:
    packages:
      - cmake
      - libxxf86vm-dev
    sources:
      - kubuntu-backports
# uncomment the following lines to override the default test script
